---
- name: 'install build tools'
  yum:
    name: git
    state: installed
  with_items:
    - gcc
    - git

- name: 'install useful debugging tools'
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - tree
    - unzip
    - vim

- name: 'add jenkins user'
  user:
    name: "{{ jenkins_user }}"
    shell: /bin/bash

- name: 'create ssh directory'
  file:
    path: "{{ jenkins_home_path }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"

- name: 'add authorized key'
  authorized_key:
    user: "{{ jenkins_user }}"
    state: present
    key: "{{ lookup('file', '../files/id_rsa.pub')}}"
    manage_dir: false
