---
- name: 'install git'
  yum:
    name: git
    state: installed

- name: 'install useful debugging tools'
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - tree
    - unzip
    - vim

- name: 'add jenkins user'
  user:
    name: "{{ jenkins_user }}"
    shell: /bin/bash

- name: 'create .ansible directory for vault password file'
  file:
    path: "{{ jenkins_home_path }}/.ansible"
    state: directory
    mode: 0700
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"

- name: 'copy vault password file'
  copy:
    src: vault-pass
    dest: "{{ jenkins_home_path }}/.ansible/vault-pass"
    mode: 0400
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"

- name: 'create ssh directory'
  file:
    path: "{{ jenkins_home_path }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"

- name: 'add authorized key'
  authorized_key:
    user: "{{ jenkins_user }}"
    state: present
    key: "{{ lookup('file', '../files/id_rsa.pub')}}"
    manage_dir: false

- name: 'copy safe vault deploy key'
  copy:
    src: safe_vault_deploy_private_key
    dest: "{{ jenkins_home_path }}/.ssh/safe_vault_deploy_private_key"
    mode: 0400
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
