---
- name: 'install musl (Ubuntu)'
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - musl-dev
    - musl-tools
  when: ansible_distribution == 'Ubuntu'

- name: 'install gcc for building musl (CentOS)'
  package:
    name: gcc
    state: present
  when: ansible_distribution == 'CentOS'

- name: 'clone musl source (CentOS)'
  git:
    repo: "{{ musl_git_url }}"
    dest: "{{ musl_src_path }}"
  when: ansible_distribution == 'CentOS'

- name: 'configure musl (CentOS)'
  command: "./configure"
  args:
    chdir: "{{ musl_src_path }}"
  when: ansible_distribution == 'CentOS'

- name: 'build musl (CentOS)'
  make:
    chdir: "{{ musl_src_path }}"
  when: ansible_distribution == 'CentOS'

- name: 'install musl (CentOS)'
  make:
    target: install
    chdir: "{{ musl_src_path }}"
  when: ansible_distribution == 'CentOS'

- name: 'symlink musl to location on path (CentOS)'
  file:
    src: "{{ musl_path }}"
    dest: "{{ musl_link_path }}"
    state: link
  when: ansible_distribution == 'CentOS'
