---
- fail:
    msg: "An IP address or hostname must be supplied for wg_server_endpoint. Run Ansible again and pass the server endpoint with -e."
  when:
    - wg_server_endpoint is not defined

- name: 'copy configuration'
  template:
    src: wg0.conf
    dest: "{{ wg_config_path }}/wg0.conf"
    mode: 0644
    owner: root
    group: root

- name: 'start the wireguard service'
  service:
    name: wg-quick@wg0
    state: started
    enabled: yes
