---
- name: 'copy configuration'
  template:
    src: wg0.conf
    dest: "{{ wg_config_path }}/wg0.conf"
    mode: 0644
    owner: root
    group: root

- name: 'enable ipv4 packet forwarding'
  lineinfile:
    path: /etc/sysctl.conf
    state: present
    line: "net.ipv4.ip_forward = 1"

- name: 'enable proxyarp'
  lineinfile:
    path: /etc/sysctl.conf
    state: present
    line: "net.ipv4.conf.all.proxy_arp = 1"

- name: 'reload kernel settings'
  command: 'sysctl -p /etc/sysctl.conf'

- name: 'start the wireguard service'
  service:
    name: wg-quick@wg0
    state: started
    enabled: yes
  when: wg_run_on_host == 'True'
