---
docker_storage_block_device: /dev/xvdc
docker_storage_mount_point: /var/lib/docker
docker_slave_ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsfyCerhUdZTjwTB1kvKIa07fjJsxvE7PlTlLCw7IDXweJC/5ki43GOmpPUTnGOh5tj2FOHAXu7oIvlyxON/Uamf5OOB4/Y/pBhTKWjaGryIBCt8ejdTrKnivt5EUnod297uWzKJnaP/WMTi2UyWej80/AxXJENKDLhX8VgcETQbfCclvb//9IagaZsG6t4rdTDT3/Wi5CYOhiz9uzu4pbN7pbnWWON0I8Dmd+ZKgsjpD9mqQogIBcqqqHd9eGqwu/BjG+h0JFUJ2ZNbkD7fyzYxPaDv5pZKcQ81aED/Q2nxxhm45D+/5cCe+yORmLNCtErMzlxZ1lwRshETv5eiNZ jacderida@localhost.localdomain
