---
provisioning_user: ansible
safe_build_infrastructure_repo_owner: maidsafe
safe_build_infrastructure_repo_branch: master
safe_build_infrastructure_repo_url: "https://github.com/{{ safe_build_infrastructure_repo_owner }}/safe-build-infrastructure.git"
safe_build_infrastructure_repo_path: "/home/{{ provisioning_user }}/safe-build-infrastructure"
virtualenv_name: venv
virtualenv_path: "{{ safe_build_infrastructure_repo_path }}/{{ virtualenv_name }}"
jq_url: "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64"
jq_install_path: "/usr/local/bin/jq"
