---
- name: 'load os specific variables'
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

# The '--ignore-installed' flag is required for OSX. See here:
# https://github.com/pypa/pip/issues/3165
- name: 'install aws cli for retrieving build artifacts from S3'
  pip:
    name: 'awscli'
    extra_args: '--ignore-installed six'

- name: 'add jenkins user (linux)'
  user:
    name: "{{ build_user }}"
    shell: /bin/bash
    groups: 'docker'
  when: ansible_distribution != 'MacOSX'

- name: 'add jenkins group (osx)'
  group:
    name: "{{ build_user }}"
    state: present
  when: ansible_distribution == 'MacOSX'

- name: 'add jenkins user (osx)'
  user:
    name: "{{ build_user }}"
    groups: "{{ build_user }}"
    shell: /bin/bash
  when: ansible_distribution == 'MacOSX'

- name: 'create ssh directory'
  file:
    path: "{{ build_user_home_path }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ build_user }}"
    group: "{{ build_user }}"

- name: 'add authorized key'
  authorized_key:
    user: "{{ build_user }}"
    state: present
    key: "{{ lookup('file', '../../../../ssh_keys/docker_build_slave_key.pub')}}"
    manage_dir: false

- name: 'create bashrc for build user'
  file:
    path: "{{ build_user_home_path }}/.bashrc"
    state: touch
    mode: 0644
    owner: "{{ build_user }}"
    group: "{{ build_user }}"
  when: ansible_distribution == 'MacOSX'

- name: 'create bash_profile for build user'
  file:
    path: "{{ build_user_home_path }}/.bash_profile"
    state: touch
    mode: 0644
    owner: "{{ build_user }}"
    group: "{{ build_user }}"
  when: ansible_distribution == 'MacOSX'

- name: 'source ~/.cargo/env in bashrc for build user'
  lineinfile:
    path: "{{ build_user_home_path }}/.bashrc"
    line: "source ~/.cargo/env"
  when: ansible_distribution == 'MacOSX'

- name: 'source ~/.bashrc in bash_profile for build user (osx)'
  lineinfile:
    path: "{{ build_user_home_path }}/.bash_profile"
    line: '[[ -s ~/.bashrc ]] && source ~/.bashrc'
  when: ansible_distribution == 'MacOSX'
