---
- name: 'copy docker configuration to /etc/sysconfig/docker'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.destination }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { destination: '/etc/sysconfig/docker', src: 'docker.centos7.j2' }
  notify:
    - restart docker

- name: 'install prerequisite packages (centos)'
  package:
    name: "{{ item }}"
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: 'add docker-ce repository (centos)'
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: 'install docker (centos)'
  package:
    name: "{{ item }}"
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
