---
- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
- include: centos.yml
  when: ansible_distribution == 'CentOS'

- name: 'create /etc/docker'
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755

- name: 'copy daemon configuration'
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644

- name: 'install python docker library for ansible docker modules'
  pip:
    name: docker
    extra_args: '--ignore-installed requests'

- name: 'create docker group'
  group:
    name: docker
  notify:
    - restart docker

- name: 'start docker'
  service:
    name: docker
    state: started
    enabled: yes

- name: 'install docker-compose'
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "/usr/bin/docker-compose-{{ docker_compose_version }}"
    owner: root
    group: docker
    mode: '0755'

- name: 'symlink docker-compose'
  file:
    src: "/usr/bin/docker-compose-{{ docker_compose_version }}"
    dest: /usr/bin/docker-compose
    state: link
    owner: root
    group: docker
    mode: '0755'
    force: yes
