---
- hosts: masters:wireguard
  become: True
  roles:
    - pip
    - docker
    - { role: wireguard, when: cloud_environment == "prod" }
    - { role: wireguard-client, when: cloud_environment == "prod" }
    - jenkins-master
