---
- hosts: masters:wireguard
  become: True
  roles:
    - hardening
    - {
        role: format_disk,
        block_device: "{{ docker_storage_block_device }}",
        mount_info: {
          name: "{{ docker_storage_mount_point }}",
          owner: "root",
          group: "root",
          mode: 0755
        },
        when: cloud_environment != "dev" or cloud_environment != "none"
      }
    - {
        role: format_disk,
        block_device: "{{ jenkins_master_block_device }}",
        mount_info: {
          name: "{{ jenkins_master_mount_point }}",
          owner: "root",
          group: "root",
          mode: 0755
        },
        when: cloud_environment != "dev" or cloud_environment != "none"
      }
    - pip
    - docker
    - {
        role: wireguard-client,
        when: cloud_environment != "dev" or cloud_environment != "none"
      }
    - jenkins-master
