---
- hosts: masters:wireguard
  become: True
  roles:
    - pip
    - docker
    - { role: wireguard, when: cloud_environment == "prod" }
    - { role: wireguard-server, when: cloud_environment == "prod" }
    - {
        role: format_disk,
        block_device: "{{ jenkins_master_block_device }}",
        mount_info: {
          name: "{{ jenkins_master_mount_point }}",
          owner: "root",
          group: "root",
          mode: 0755
        },
        when: cloud_environment == "prod"
      }
    - jenkins-master
