---
- hosts: osx_slaves
  become: True
  tasks:
    - name: 'stop wireguard (if not running this task will error but that is fine) (macOS)'
      command: "wg-quick down {{ item }}"
      ignore_errors: yes
      with_items:
        - wg0
        - wg0-dev
        - wg0-staging
        - wg0-prod
    - name: 'uninstall awscli'
      pip:
        name: 'awscli'
        state: absent
      ignore_errors: yes
    - name: 'uninstall pip'
      pip:
        name: 'pip'
        state: absent
      ignore_errors: yes
    - name: 'remove jenkins user'
      user:
        name: 'jenkins'
        state: absent
      ignore_errors: yes
    - name: 'remove jenkins group'
      group:
        name: 'jenkins'
        state: absent
      ignore_errors: yes
    - name: 'remove jenkins user home directory'
      file:
        path: /Users/jenkins
        state: absent
      ignore_errors: yes
    - name: 'uninstall java'
      homebrew_cask:
        name: homebrew/cask-versions/adoptopenjdk8
        state: absent
      become: yes
      become_user: qamaidsafe
      ignore_errors: yes
    - name: 'uninstall caskroom/versions'
      homebrew_tap:
        name: homebrew/cask-versions
        state: absent
      ignore_errors: yes
    - name: 'uninstall wireguard'
      homebrew:
        name: wireguard-tools
        state: absent
      ignore_errors: yes
