---
- hosts: proxies:wireguard
  become: True
  roles:
    - hardening
    - lets-encrypt
    - haproxy
    - {
        role: wireguard,
        when: cloud_environment != "dev" or cloud_environment != "none"
      }
    - {
        role: wireguard-server,
        when: cloud_environment != "dev" or cloud_environment != "none"
      }
