---
- hosts: proxies:wireguard
  become: True
  roles:
    - hardening
    - lets-encrypt
    - haproxy
    - {
        role: wireguard,
        when: cloud_environment == "prod" or cloud_environment == "staging"
      }
    - {
        role: wireguard-server,
        when: cloud_environment == "prod" or cloud_environment == "staging"
      }
